name: check x86 gcc

on:
  schedule:
    - cron:  '0 21 * * ?'
    - cron:  '0 6 * * ?'
  workflow_dispatch:

jobs:
  test-sim:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        os:     [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo ./.github/setup-apt.sh
      - name: check
        run: |
          git submodule update --init --depth=1
          make test
